version: 2
updates:
  - package-ecosystem: "uv"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"

  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "daily"
