# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

PROPERTY_TO_MODEL_FIELD = {
    "youngs_modulus": "Young's Modulus",
    "poissons_ratio": "Poisson's Ratio",
    "youngs_modulus_x": "Young's Modulus X direction",
    "youngs_modulus_y": "Young's Modulus Y direction",
    "youngs_modulus_z": "Young's Modulus Z direction",
    "poissons_ratio_xy": "Poisson's Ratio XY",
    "poissons_ratio_xz": "Poisson's Ratio XZ",
    "poissons_ratio_yz": "Poisson's Ratio YZ",
    "shear_modulus_xy": "Shear Modulus XY",
    "shear_modulus_xz": "Shear Modulus XZ",
    "shear_modulus_yz": "Shear Modulus YZ",
    "yield_stress_ratio_x": "Yield stress ratio in X direction",
    "yield_stress_ratio_y": "Yield stress ratio in Y direction",
    "yield_stress_ratio_z": "Yield stress ratio in Z direction",
    "yield_stress_ratio_xy": "Yield stress ratio in XY direction",
    "yield_stress_ratio_xz": "Yield stress ratio in XZ direction",
    "yield_stress_ratio_yz": "Yield stress ratio in YZ direction",
    "stress": "Stress",
    "initial_yield_stress": "Initial Yield Stress",
    "linear_coefficient": "Linear Coefficient",
    "exponential_coefficient": "Exponential Coefficient",
    "exponential_saturation_parameter": "Exponential Saturation Parameter",
    "density": "Density",
    "column_1": "D[*,1]",
    "column_2": "D[*,2]",
    "column_3": "D[*,3]",
    "column_4": "D[*,4]",
    "column_5": "D[*,5]",
    "column_6": "D[*,6]",
    "thermal_conductivity": "Thermal Conductivity",
    "thermal_conductivity_x": "Thermal Conductivity X direction",
    "thermal_conductivity_y": "Thermal Conductivity Y direction",
    "thermal_conductivity_z": "Thermal Conductivity Z direction",
    "coefficient_of_thermal_expansion": "Coefficient of Thermal Expansion",
    "coefficient_of_thermal_expansion_x": "Coefficient of Thermal Expansion X direction",
    "coefficient_of_thermal_expansion_y": "Coefficient of Thermal Expansion Y direction",
    "coefficient_of_thermal_expansion_z": "Coefficient of Thermal Expansion Z direction",
    "zero_thermal_strain_reference_temperature": "Zero-Thermal-Strain Reference Temperature",
    "material_property": "Material Property",
    "yield_stress_ratio_x_for_plasticity": "Yield stress ratio in X direction for plasticity",
    "yield_stress_ratio_y_for_plasticity": "Yield stress ratio in Y direction for plasticity",
    "yield_stress_ratio_z_for_plasticity": "Yield stress ratio in Z direction for plasticity",
    "yield_stress_ratio_xy_for_plasticity": "Yield stress ratio in XY direction for plasticity",
    "yield_stress_ratio_xz_for_plasticity": "Yield stress ratio in XZ direction for plasticity",
    "yield_stress_ratio_yz_for_plasticity": "Yield stress ratio in YZ direction for plasticity",
    "yield_stress_ratio_x_for_creep": "Yield stress ratio in X direction for creep",
    "yield_stress_ratio_y_for_creep": "Yield stress ratio in Y direction for creep",
    "yield_stress_ratio_z_for_creep": "Yield stress ratio in Z direction for creep",
    "yield_stress_ratio_xy_for_creep": "Yield stress ratio in XY direction for creep",
    "yield_stress_ratio_xz_for_creep": "Yield stress ratio in XZ direction for creep",
    "yield_stress_ratio_yz_for_creep": "Yield stress ratio in YZ direction for creep",
    "yield_stress": "Yield Stress",
    "material_constant_gamma_1": "Material Constant γ1",
    "material_constant_c_1": "Material Constant C1",
    "material_constant_gamma_2": "Material Constant γ2",
    "material_constant_c_2": "Material Constant C2",
    "material_constant_gamma_3": "Material Constant γ3",
    "material_constant_c_3": "Material Constant C3",
    "material_constant_gamma_4": "Material Constant γ4",
    "material_constant_c_4": "Material Constant C4",
    "material_constant_gamma_5": "Material Constant γ5",
    "material_constant_c_5": "Material Constant C5",
    "creep_constant_1": "Creep Constant 1",
    "creep_constant_2": "Creep Constant 2",
    "creep_constant_3": "Creep Constant 3",
    "creep_constant_4": "Creep Constant 4",
    "von_mises": "Von Mises",
    "tensile_x_direction": "Tensile X direction",
    "tensile_y_direction": "Tensile Y direction",
    "tensile_z_direction": "Tensile Z direction",
    "compressive_x_direction": "Compressive X direction",
    "compressive_y_direction": "Compressive Y direction",
    "compressive_z_direction": "Compressive Z direction",
    "shear_xy": "Shear XY",
    "shear_xz": "Shear XZ",
    "shear_yz": "Shear YZ",
    "fabric_fiber_angle": "Fabric Fiber Angle",
    "compressive_inclination_xz": "Compressive Inclination XZ",
    "compressive_inclination_yz": "Compressive Inclination YZ",
    "tensile_inclination_xz": "Tensile Inclination XZ",
    "tensile_inclination_yz": "Tensile Inclination YZ",
    "interface_weakening_factor": "Interface Weakening Factor",
    "degradation_parameter_s": "Degradation Parameter s",
    "degradation_parameter_m": "Degradation Parameter M",
    "fiber_angle": "Fiber Angle",
    "red": "Red",
    "green": "Green",
    "blue": "Blue",
    "coupling_coefficient_xy": "Coupling Coefficient XY",
    "coupling_coefficient_xz": "Coupling Coefficient XZ",
    "coupling_coefficient_yz": "Coupling Coefficient YZ",
    "viscosity": "Viscosity",
    "speed_of_sound": "Speed of Sound",
    "specific_heat": "Specific Heat",
    "fracture_toughness_ratio": "Fracture Toughness Ratio",
    "longitudinal_friction_coefficient": "Longitudinal Friction Coefficient",
    "transverse_friction_coefficient": "Transverse Friction Coefficient",
    "fracture_angle_under_compression": "Fracture Angle Under Compression",
}
