# Copyright (C) 2022 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Matml Keys
ALGORITHM_TYPE_KEY = "AlgorithmType"
BEHAVIOR_KEY = "Behavior"
BULK_DETAILS_KEY = "BulkDetails"
CACHED_KEY = "Cached"
DASH_KEY = "-"
DATA_KEY = "Data"
DATA_TRANSFER_ID_KEY = "DataTransferID"
DEFAULT_DATA_KEY = "Default Data"
DEPENDENT_KEY = "Dependent"
EXTRAPOLATION_TYPE_KEY = "ExtrapolationType"
FLOAT_KEY = "float"
FORMAT_KEY = "format"
ID_KEY = "id"
INDEPENDENT_KEY = "Independent"
INTERPOLATION_OPTIONS_KEY = "Interpolation Options"
LOWER_LIMIT_KEY = "Lower Limit"
MATERIAL_KEY = "MATERIAL"
MATERIALS_ELEMENT_KEY = "Materials"
MATML_DOC_KEY = "MatML_Doc"
METADATA_KEY = "Metadata"
NAME_KEY = "name"
NORMALIZED_KEY = "Normalized"
NOTES_KEY = "Notes"
NOTES_TEXT = "Engineering data xml file generated by pyMaterials."
OPTIONS_VARIABLE_KEY = "Options Variable"
PARAMETER_DETAILS_KEY = "ParameterDetails"
PARAMETER_ID = "pa"
PARAMETER_KEY = "parameter"
PARAMETER_VALUE_KEY = "ParameterValue"
POWER_KEY = "power"
PROPERTY_DATA_KEY = "PropertyData"
PROPERTY_DETAILS_KEY = "PropertyDetails"
PROPERTY_ID = "pr"
PROPERTY_KEY = "property"
QUALIFIER_KEY = "Qualifier"
ROOT_ELEMENT = "EngineeringData"
STRING_KEY = "string"
UNIT_KEY = "Unit"
UNITLESS_KEY = "Unitless"
UNITS_KEY = "Units"
UNITS_NAME_KEY = "UnitsName"
UPPER_LIMIT_KEY = "Upper Limit"
USER_MAT_CONSTANT_KEY = "UserMat Constant"
VARIABLE_TYPE_KEY = "Variable Type"
VERSION = "18.0.0.60"
VERSION_DATE = "29.08.2016 15:02:00"
WBTRANSFER_KEY = "ANSYSWBTransferData"
